### ISSUE TITLE
Unable to purge attachments

### ISSUE THREAD

**Issue by nsylke** [sylkellc/typicalbot#175]
### Description

The `$purge` command will not delete messages that are only attachments.

### Reproduction Steps

1. Send an attachment in a channel
2. Run `$purge 10` 

### Observed Behavior

The message with the attachment is not deleted

### Expected Behavior

The message with the attachment should be deleted

### Additional Details

- Operating System: Ubuntu 18.04
- TypicalBot Version:  3.2.1

### Have You...?
- [X] I have checked for previous issues reporting this problem.
- [X] I have tried to reproduce this problem on the latest `master` commit.
- [X] I have tried to reproduce this problem on the official bot operated by TypicalBot.

**Comment by tjrgg** [comment]
Unable to reproduce.

Messages with attachments are deleted when using the reproduction steps provided.
