### ISSUE TITLE
Purge webhooks

### ISSUE THREAD

**Issue by nsylke** [sylkellc/typicalbot#180]
### Description

Currently the `$purge` command will not remove webhook messages. We should should make a check for webhook messages along with another subcommand. 

### Usefulness

People want to purge webhooks! 

### Have You...?
- [X] I have checked previous issues to see if my enhancement or feature has already been suggested.
- [X] I have checked previous issues and pull requests to see if my enhancement or feature has already been completed for an upcoming release.

**Comment by Skillz4Killz** [comment]
This appears to most likely be caused by line 47 in purge command. Is that condition useful?

**Comment by nsylke** [comment]
> This appears to most likely be caused by line 47 in purge command. Is that condition useful?

I don't think so. I would say its safe to remove.

**Comment by tjrgg** [comment]
@Skillz4Killz I believe the purpose of that was to check for a guild, so perhaps change that to `!msg.guild`.
