### ISSUE TITLE
Automatically delete invite posted warning after a few seconds

### ISSUE THREAD

**Issue by nsylke** [sylkellc/typicalbot#185]
### Description

Automatically delete invite posted warning after a few seconds
![DiscordCanary_3EMf7XFmmO](https://user-images.githubusercontent.com/19676879/80230184-303e9900-8617-11ea-92be-c5c27f997f9a.png)

### Usefulness

The invite posted is already logged, no reason to keep the warning in chat after a few seconds.

### Have You...?
- [X] I have checked previous issues to see if my enhancement or feature has already been suggested.
- [X] I have checked previous issues and pull requests to see if my enhancement or feature has already been completed for an upcoming release.

**Comment by TobiasFeld22** [comment]
Maybe only auto delete if modlogs are enabled?

**Comment by tjrgg** [comment]
@TobiasFeld22, I'd rather not do that unless someone asks for it.

**Comment by TobiasFeld22** [comment]
That's a fair point
