### ISSUE TITLE
`purge` command fails to purge messages from non-members

### ISSUE THREAD

**Issue by tjrgg** [sylkellc/typicalbot#191]
### Description

The `purge` command excludes messages from users that are no longer members of the server (left or kicked).

### Reproduction Steps

- Have member send a message.
- Have member leave / kick member.
- Run `purge` to try and purge their messages.

### Observed Behavior

The command acts as if the messages don't exist and ignores them. Instead, the command purges messages prior to messages sent by the old member.

### Expected Behavior

The command includes messages sent by an ex-member.

### Additional Details

- Operating System: 
- TypicalBot Version: 3.2.4

### Have You...?
- [x] I have checked for previous issues reporting this problem.
- [x] I have tried to reproduce this problem on the latest `master` commit.
- [x] I have tried to reproduce this problem on the official bot operated by TypicalBot.

**Comment by Skillz4Killz** [comment]
Will be fixed most likely in the next deploy.
