### ISSUE TITLE
Account age on member join

### ISSUE THREAD

**Issue by nsylke** [sylkellc/typicalbot#210]
### Description

Let's create a setting to show account age when a user joins - this should be logged in the current member join log. 

Additionally, lets automatically log "New Account" (bypass the setting) when the account is under 15 minutes old - this is a threshold we control and may change in the future - this should be logged in the current member join log as well.

### Usefulness

Help detect new users/spam/bots

### Have You...?
- [X] I have checked previous issues to see if my enhancement or feature has already been suggested.
- [X] I have checked previous issues and pull requests to see if my enhancement or feature has already been completed for an upcoming release.

**Comment by tjrgg** [comment]
I don't think a setting is necessary for this. I think it would be okay to include this as normal behavior.

**Comment by nsylke** [comment]
@Skillz4Killz Feel free to make PR for this. 

```diff
# Account Age greater than 15 minutes
Account Age: 30 days

# Account Age less than 15 minutes
Account Age: 14 mins (New Account)
```
