### ISSUE TITLE
Emoji used incompatible with (older) Android phones

### ISSUE THREAD

**Issue by TobiasFeld22** [sylkellc/typicalbot#229]
### Description

Using the punch / slap commands, the bot sends a fist / wave icon with a skin color, but that's not supported for older versions of android (in the Discord app at least).

### Reproduction Steps

get an android phone
type `$punch` / `$slap`

### Observed Behavior
See image
![image of issue](https://cdn.discordapp.com/attachments/704004244788740148/706294874680459355/Screenshot_20200502-200318_Discord.jpg)

### Expected Behavior

![image of exp](https://cdn.discordapp.com/attachments/356067655234355210/710505182332715089/DiscordCanary_Q9PNOPeqQ8.png)

### Additional Details

- Operating System: Observed on android 9.0
- TypicalBot Version: 3.5.0

### Have You...?
- [x] I have checked for previous issues reporting this problem.
- [x] I have tried to reproduce this problem on the latest `master` commit.
- [x] I have tried to reproduce this problem on the official bot operated by TypicalBot.

**Comment by tjrgg** [comment]
Technically, this is a bug with Discord, not TypicalBot. However, we could update our use of emojis to not use a certain skin tone as a workaround.

**Comment by nsylke** [comment]
@tjrgg It's probably best to switch all skin tone emojis to non-skin tone emojis. Feel free to make a PR.
