### ISSUE TITLE
[4.x] TypicalBot Product Analytics

### ISSUE THREAD

**Issue by Skillz4Killz** [sylkellc/typicalbot#92]
## Enhancement Suggestion
Product analytics that better shows how the bot is being used.

### Description

![image](https://user-images.githubusercontent.com/23035000/68554364-d72ad200-03f5-11ea-8e06-09d621db228a.png)

### Usefulness

Gives a better understanding of what part of the bot is most important to majority of users.

### Have You...?
- [ ] I have checked previous issues to see if my enhancement or feature has already been suggested.
- [ ] I have checked previous issues and pull requests to see if my enhancement or feature has already been completed for an upcoming release.

**Comment by tjrgg** [comment]
I've been doing some work in this area in determining the best way to implement some telemetry of some kind, but there's some considerations that need to be made, most importantly of which is user privacy.

**Comment by nsylke** [comment]
I've been working on a solution, projecting it to be released in 3.2 or 3.3

**Comment by nsylke** [comment]
Implemented as of e8ebe70.
